# -*- coding: utf-8 -*-
"""COVID-19 Data Analysis & Visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pS-lppR0I5P04sKTZ-Bpw4oSM1-NPCrw

**covid 19 analysis**
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

#Reading data as dataframe
covid_data = pd.read_json('covid_states_daily.json')
print(covid_data)

#Remarks : Using pandas dataframe directly, json reading is not effective

import json
import pandas as pd

#Using json.read(), data is stored as a dictionary
f = open('covid_states_daily.json','r')
covid_data = json.load(f)
#print(type(covid_data))
print(covid_data)

#remove the outer dictionary
covid_data = covid_data['states_daily']
#print(type(covid_data))
print(covid_data)

#json_normalize converts json into a flat table structure
covid_data = pd.json_normalize(covid_data)
#Now the data is in the form of a dataframe
#print(type(covid_data))
print(covid_data)

#Filter on status='Confirmed'
covid_data = covid_data[covid_data.status == 'Confirmed']

#Drop the non-numeric date and status columns
covid_data.drop('date',axis=1, inplace=True)
covid_data.drop('status',axis=1, inplace=True)

#Create datemyd as index
covid_data.set_index('dateymd',inplace=True)
#print(covid_data.head(3))

#Convert all table data into numeric
covid_data = covid_data.apply(pd.to_numeric)

#We'll take 5 values at the tail for better visualization
covid_data = covid_data.tail(5)

#View data as table
#print(covid_data.to_markdown())

#View table in Grid format
print(covid_data.to_markdown(tablefmt="grid"))


f.close()

# Read the JSON file
# Get the Flat table structure
# filter out for the state of Karnataka
# plot the line graphs for Confirmed and recovered cases


#Using json.read(), data is stored as a dictionary
f = open('covid_states_daily.json','r')
covid_data = json.load(f)
#print(type(covid_data))
#print(covid_data)

#remove the outer dictionary
covid_data = covid_data['states_daily']
#print(type(covid_data))
print(covid_data)

#json_normalize converts json into a flat table structure
covid_data = pd.json_normalize(covid_data)
#Now the data is in the form of a dataframe
#print(type(covid_data))
print(covid_data)

f.close()

# drop all columns except column ka

ka_data = covid_data[['ka','status','dateymd']]

# make the column 'dateymd' as the index
ka_data.set_index('dateymd',inplace=True)

print(ka_data)

confirmed_ka_data = ka_data[ka_data.status == 'Confirmed']
# drop the column status
confirmed_ka_data = confirmed_ka_data.drop('status', axis=1)
confirmed_ka_data = confirmed_ka_data.apply(pd.to_numeric)

recoverd_ka_data = ka_data[ka_data.status == 'Recovered']
#drop the column status
recoverd_ka_data = recoverd_ka_data.drop('status', axis=1)
recoverd_ka_data = recoverd_ka_data.apply(pd.to_numeric)

# plot the line graph for the above 2 data frames
# use labels and legend to show which color is what

# increase the figure size
plt.figure(figsize=(25,8))

# make x-axis label vertical


plt.plot(confirmed_ka_data, label='Confirmed')
plt.plot(recoverd_ka_data, label='Recovered')
plt.xticks(rotation='vertical')
plt.xlabel('Date')
plt.ylabel('Number of Cases')
plt.title('COVID-19 in Karnataka')
plt.legend()
plt.show()

#Let's style the tabulation now
covid_data.style.highlight_max(color='red')

#Let's style the tabulation now
#Default hihglight colour is yellow
covid_data.style.highlight_min()

covid_data.style.highlight_max(color='red').highlight_min(color='green')

covid_data.style.background_gradient(cmap='Reds')

covid_data.style.bar()

covid_data[['ap','ka','kl','tn']].style.bar(color='green')

covid_data[['ap','ka','kl','tn']].style.background_gradient(cmap='Reds')

"""Covid Data Ploting"""

# Import the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Read data from the CSV file 'case_time_series.csv' into a Pandas DataFrame
data = pd.read_csv('case_time_series.csv')

# Extract specific columns from the DataFrame:
# - Y represents a column from the 2nd index (1-based) containing the Y values
# - R represents a column from the 4th index (1-based) containing the R values
# - D represents a column from the 6th index (1-based) containing the D values
# - X represents a column from the 1st index (0-based) containing the X values
Y = data.iloc[61:, 1].values  # You are extracting values from the 62nd row (0-based index) : Daily Confirmed
R = data.iloc[61:, 3].values  # Similarly, extracting values from the 62nd row : Recovered
D = data.iloc[61:, 5].values # Daily Deceased
X = data.iloc[61:, 0]  # Here, you're extracting the values from the 62nd row as well : Date

# Create a line plot using X and Y values
plt.figure(figsize=(25,8))
plt.plot(X, Y)

# Display the plot
plt.show()



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('case_time_series.csv')

Y = data.iloc[61:,1].values
R = data.iloc[61:,3].values
D = data.iloc[61:,5].values
X = data.iloc[61:,0]

plt.figure(figsize=(25,8))

ax = plt.axes()
ax.grid(linewidth=0.4, color='#8f8f8f')

ax.set_facecolor("black")
ax.set_xlabel('\nDate',size=25,color='#4bb4f2')
ax.set_ylabel('Number of Confirmed Cases\n',
			size=25,color='#4bb4f2')

ax.plot(X,Y,
		color='#1F77B4',
		marker='o',
		linewidth=4,
		markersize=15,
		markeredgecolor='#9b0310')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('case_time_series.csv')

Y = data.iloc[61:,1].values
R = data.iloc[61:,3].values
D = data.iloc[61:,5].values
X = data.iloc[61:,0]

plt.figure(figsize=(25,8))

ax = plt.axes()
ax.grid(linewidth=0.4, color='#8f8f8f')

ax.set_facecolor("black")
ax.set_xlabel('\nDate',size=25,color='#4bb4f2')
ax.set_ylabel('Number of Confirmed Cases\n',
			size=25,color='#4bb4f2')

plt.xticks(rotation='vertical',size='20',color='red')
plt.yticks(size=20,color='red')
plt.tick_params(size=20,color='red')

for i,j in zip(X,Y):
	ax.annotate(str(j),xy=(i,j+100),color='white',size='13')

ax.annotate('Second Lockdown 15th April',
			xy=(15.2, 860),
			xytext=(19.9,500),
			color='white',
			size='25',
			arrowprops=dict(color='white',
							linewidth=0.025))

plt.title("COVID-19 IN : Daily Confirmed\n",
		size=50,color='#28a9ff')

ax.plot(X,Y,
		color='#1F77B4',
		marker='o',
		linewidth=4,
		markersize=15,
		markeredgecolor='#035E9B')
